# coding: utf-8

"""
    Food Data Central API

    The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.nutrient_analysis_details import NutrientAnalysisDetails  # noqa: E501

class TestNutrientAnalysisDetails(unittest.TestCase):
    """NutrientAnalysisDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NutrientAnalysisDetails:
        """Test NutrientAnalysisDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NutrientAnalysisDetails`
        """
        model = NutrientAnalysisDetails()  # noqa: E501
        if include_optional:
            return NutrientAnalysisDetails(
                sub_sample_id = 343866,
                amount = 0,
                nutrient_id = 1005,
                lab_method_description = '10.2135/cropsci2017.04.0244',
                lab_method_original_description = '',
                lab_method_link = 'https://doi.org/10.2135/cropsci2017.04.0244',
                lab_method_technique = 'DOI for Beans',
                nutrient_acquisition_details = [
                    openapi_client.models.nutrient_acquisition_details.NutrientAcquisitionDetails(
                        sample_unit_id = 321632, 
                        purchase_date = '12/2/2005', 
                        store_city = 'TRUSSVILLE', 
                        store_state = 'AL', )
                    ]
            )
        else:
            return NutrientAnalysisDetails(
        )
        """

    def testNutrientAnalysisDetails(self):
        """Test NutrientAnalysisDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
