# coding: utf-8

"""
    Food Data Central API

    The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.inline_response200 import InlineResponse200

class TestInlineResponse200(unittest.TestCase):
    """InlineResponse200 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200:
        """Test InlineResponse200
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200`
        """
        model = InlineResponse200()
        if include_optional:
            return InlineResponse200(
                data_type = 'SR Legacy',
                description = 'Beef curry',
                fdc_id = 337985,
                food_nutrients = [
                    openapi_client.models.food_nutrient.FoodNutrient(
                        id = 167514, 
                        amount = 0, 
                        data_points = 49, 
                        min = 73.73, 
                        max = 91.8, 
                        median = 90.3, 
                        type = 'FoodNutrient', 
                        nutrient = openapi_client.models.nutrient.Nutrient(
                            id = 1005, 
                            number = '305', 
                            name = 'Carbohydrate, by difference', 
                            rank = 1110, 
                            unit_name = 'g', ), 
                        food_nutrient_derivation = openapi_client.models.food_nutrient_derivation.FoodNutrientDerivation(
                            id = 75, 
                            code = 'LCCD', 
                            description = 'Calculated from a daily value percentage per serving size measure', 
                            food_nutrient_source = openapi_client.models.food_nutrient_source.FoodNutrientSource(
                                id = 9, 
                                code = '12', 
                                description = 'Manufacturer's analytical; partial documentation', ), ), 
                        nutrient_analysis_details = openapi_client.models.nutrient_analysis_details.NutrientAnalysisDetails(
                            sub_sample_id = 343866, 
                            amount = 0, 
                            nutrient_id = 1005, 
                            lab_method_description = '10.2135/cropsci2017.04.0244', 
                            lab_method_original_description = '', 
                            lab_method_link = 'https://doi.org/10.2135/cropsci2017.04.0244', 
                            lab_method_technique = 'DOI for Beans', 
                            nutrient_acquisition_details = [
                                openapi_client.models.nutrient_acquisition_details.NutrientAcquisitionDetails(
                                    sample_unit_id = 321632, 
                                    purchase_date = '12/2/2005', 
                                    store_city = 'TRUSSVILLE', 
                                    store_state = 'AL', )
                                ], ), )
                    ],
                publication_date = '4/1/2019',
                brand_owner = 'Kar Nut Products Company',
                gtin_upc = '077034085228',
                ndb_number = 11090,
                food_code = '27116100',
                available_date = '8/18/2018',
                data_source = 'LI',
                food_class = 'Survey',
                household_serving_full_text = '1 ONZ',
                ingredients = 'PEANUTS (PEANUTS, PEANUT AND/OR SUNFLOWER OIL). RAISINS. DRIED CRANBERRIES (CRANBERRIES, SUGAR, SUNFLOWER OIL). SUNFLOWER KERNELS AND ALMONDS (SUNFLOWER KERNELS AND ALMONDS, PEANUT AND/OR SUNFLOWER OIL).',
                modified_date = '8/18/2018',
                serving_size = 28,
                serving_size_unit = 'g',
                preparation_state_code = 'UNPREPARED',
                branded_food_category = 'Popcorn, Peanuts, Seeds & Related Snacks',
                trade_channel = [CHILD_NUTRITION_FOOD_PROGRAMS, GROCERY],
                gpc_class_code = 50161800,
                food_update_log = [
                    openapi_client.models.food_update_log.FoodUpdateLog(
                        fdc_id = 534358, 
                        available_date = '8/18/2018', 
                        brand_owner = 'Kar Nut Products Company', 
                        data_source = 'LI', 
                        data_type = 'Branded', 
                        description = 'NUT 'N BERRY MIX', 
                        food_class = 'Branded', 
                        gtin_upc = '077034085228', 
                        household_serving_full_text = '1 ONZ', 
                        ingredients = 'PEANUTS (PEANUTS, PEANUT AND/OR SUNFLOWER OIL). RAISINS. DRIED CRANBERRIES (CRANBERRIES, SUGAR, SUNFLOWER OIL). SUNFLOWER KERNELS AND ALMONDS (SUNFLOWER KERNELS AND ALMONDS, PEANUT AND/OR SUNFLOWER OIL).', 
                        modified_date = '8/18/2018', 
                        publication_date = '4/1/2019', 
                        serving_size = 28, 
                        serving_size_unit = 'g', 
                        branded_food_category = 'Popcorn, Peanuts, Seeds & Related Snacks', 
                        changes = 'Nutrient Added, Nutrient Updated', 
                        food_attributes = [
                            openapi_client.models.food_attribute.FoodAttribute(
                                id = 25117, 
                                sequence_number = 1, 
                                value = 'Moisture change: -5.0%', 
                                food_attribute_type = openapi_client.models.food_attribute_food_attribute_type.FoodAttribute_FoodAttributeType(
                                    id = 1002, 
                                    name = 'Adjustments', 
                                    description = 'Adjustments made to foods, including moisture and fat changes.', ), )
                            ], )
                    ],
                label_nutrients = openapi_client.models.branded_food_item_label_nutrients.BrandedFoodItem_labelNutrients(
                    fat = openapi_client.models.branded_food_item_label_nutrients_fat.BrandedFoodItem_labelNutrients_fat(
                        value = 8.9992, ), 
                    saturated_fat = openapi_client.models.branded_food_item_label_nutrients_saturated_fat.BrandedFoodItem_labelNutrients_saturatedFat(
                        value = 0.9996, ), 
                    trans_fat = openapi_client.models.branded_food_item_label_nutrients_trans_fat.BrandedFoodItem_labelNutrients_transFat(
                        value = 0, ), 
                    cholesterol = openapi_client.models.branded_food_item_label_nutrients_trans_fat.BrandedFoodItem_labelNutrients_transFat(
                        value = 0, ), 
                    sodium = , 
                    carbohydrates = openapi_client.models.branded_food_item_label_nutrients_carbohydrates.BrandedFoodItem_labelNutrients_carbohydrates(
                        value = 12.0008, ), 
                    fiber = openapi_client.models.branded_food_item_label_nutrients_fiber.BrandedFoodItem_labelNutrients_fiber(
                        value = 1.988, ), 
                    sugars = openapi_client.models.branded_food_item_label_nutrients_sugars.BrandedFoodItem_labelNutrients_sugars(
                        value = 7.9996, ), 
                    protein = openapi_client.models.branded_food_item_label_nutrients_protein.BrandedFoodItem_labelNutrients_protein(
                        value = 4.0012, ), 
                    calcium = openapi_client.models.branded_food_item_label_nutrients_calcium.BrandedFoodItem_labelNutrients_calcium(
                        value = 19.88, ), 
                    iron = openapi_client.models.branded_food_item_label_nutrients_iron.BrandedFoodItem_labelNutrients_iron(
                        value = 0.7196, ), 
                    potassium = openapi_client.models.branded_food_item_label_nutrients_potassium.BrandedFoodItem_labelNutrients_potassium(
                        value = 159.88, ), 
                    calories = openapi_client.models.branded_food_item_label_nutrients_calories.BrandedFoodItem_labelNutrients_calories(
                        value = 140, ), ),
                foot_note = 'Source number reflects the actual number of samples analyzed for a nutrient. Repeat nutrient analyses may have been done on the same sample with the values shown.',
                is_historical_reference = True,
                scientific_name = 'Brassica oleracea var. italica',
                food_category = openapi_client.models.food_category.FoodCategory(
                    id = 11, 
                    code = '1100', 
                    description = 'Vegetables and Vegetable Products', ),
                food_components = [
                    openapi_client.models.food_component.FoodComponent(
                        id = 59929, 
                        name = 'External fat', 
                        data_points = 24, 
                        gram_weight = 2.1, 
                        is_refuse = True, 
                        min_year_acquired = 2011, 
                        percent_weight = 0.5, )
                    ],
                food_portions = [
                    openapi_client.models.food_portion.FoodPortion(
                        id = 135806, 
                        amount = 1, 
                        data_points = 9, 
                        gram_weight = 91, 
                        min_year_acquired = 2011, 
                        modifier = '10205', 
                        portion_description = '1 cup', 
                        sequence_number = 1, 
                        measure_unit = openapi_client.models.measure_unit.MeasureUnit(
                            id = 999, 
                            abbreviation = 'undetermined', 
                            name = 'undetermined', ), )
                    ],
                input_foods = [
                    openapi_client.models.input_food_survey.InputFoodSurvey(
                        id = 18146, 
                        amount = 1.5, 
                        food_description = 'Spices, curry powder', 
                        ingredient_code = 2015, 
                        ingredient_description = 'Spices, curry powder', 
                        ingredient_weight = 9.45, 
                        portion_code = '21000', 
                        portion_description = '1 tablespoon', 
                        sequence_number = 6, 
                        survey_flag = 0, 
                        unit = 'TB', 
                        input_food = openapi_client.models.survey_food_item.SurveyFoodItem(
                            fdc_id = 337985, 
                            datatype = 'Survey (FNDDS)', 
                            description = 'Beef curry', 
                            end_date = '12/31/2014', 
                            food_class = 'Survey', 
                            food_code = '27116100', 
                            publication_date = '4/1/2019', 
                            start_date = '1/1/2013', 
                            food_attributes = [
                                openapi_client.models.food_attribute.FoodAttribute(
                                    id = 25117, 
                                    sequence_number = 1, 
                                    value = 'Moisture change: -5.0%', 
                                    food_attribute_type = openapi_client.models.food_attribute_food_attribute_type.FoodAttribute_FoodAttributeType(
                                        id = 1002, 
                                        name = 'Adjustments', 
                                        description = 'Adjustments made to foods, including moisture and fat changes.', ), )
                                ], 
                            food_portions = [
                                openapi_client.models.food_portion.FoodPortion(
                                    id = 135806, 
                                    amount = 1, 
                                    data_points = 9, 
                                    gram_weight = 91, 
                                    min_year_acquired = 2011, 
                                    modifier = '10205', 
                                    portion_description = '1 cup', 
                                    sequence_number = 1, 
                                    measure_unit = openapi_client.models.measure_unit.MeasureUnit(
                                        id = 999, 
                                        abbreviation = 'undetermined', 
                                        name = 'undetermined', ), )
                                ], 
                            input_foods = [
                                openapi_client.models.input_food_survey.InputFoodSurvey(
                                    id = 18146, 
                                    amount = 1.5, 
                                    food_description = 'Spices, curry powder', 
                                    ingredient_code = 2015, 
                                    ingredient_description = 'Spices, curry powder', 
                                    ingredient_weight = 9.45, 
                                    portion_code = '21000', 
                                    portion_description = '1 tablespoon', 
                                    sequence_number = 6, 
                                    survey_flag = 0, 
                                    unit = 'TB', 
                                    retention_factor = openapi_client.models.retention_factor.RetentionFactor(
                                        id = 235, 
                                        code = 3460, 
                                        description = 'VEG, ROOTS, ETC, SAUTEED', ), )
                                ], 
                            wweia_food_category = openapi_client.models.wweia_food_category.WweiaFoodCategory(
                                wweia_food_category_code = 3002, 
                                wweia_food_category_description = 'Meat mixed dishes', ), ), 
                        retention_factor = openapi_client.models.retention_factor.RetentionFactor(
                            id = 235, 
                            code = 3460, 
                            description = 'VEG, ROOTS, ETC, SAUTEED', ), )
                    ],
                nutrient_conversion_factors = [
                    openapi_client.models.nutrient_conversion_factors.NutrientConversionFactors(
                        type = '.ProteinConversionFactor', 
                        value = 6.25, )
                    ],
                datatype = 'Survey (FNDDS)',
                end_date = '12/31/2014',
                start_date = '1/1/2013',
                food_attributes = [
                    openapi_client.models.food_attribute.FoodAttribute(
                        id = 25117, 
                        sequence_number = 1, 
                        value = 'Moisture change: -5.0%', 
                        food_attribute_type = openapi_client.models.food_attribute_food_attribute_type.FoodAttribute_FoodAttributeType(
                            id = 1002, 
                            name = 'Adjustments', 
                            description = 'Adjustments made to foods, including moisture and fat changes.', ), )
                    ],
                wweia_food_category = openapi_client.models.wweia_food_category.WweiaFoodCategory(
                    wweia_food_category_code = 3002, 
                    wweia_food_category_description = 'Meat mixed dishes', )
            )
        else:
            return InlineResponse200(
                data_type = 'SR Legacy',
                description = 'Beef curry',
                fdc_id = 337985,
        )
        """

    def testInlineResponse200(self):
        """Test InlineResponse200"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
