# coding: utf-8

"""
    Food Data Central API

    The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.abridged_food_item import AbridgedFoodItem  # noqa: E501

class TestAbridgedFoodItem(unittest.TestCase):
    """AbridgedFoodItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AbridgedFoodItem:
        """Test AbridgedFoodItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AbridgedFoodItem`
        """
        model = AbridgedFoodItem()  # noqa: E501
        if include_optional:
            return AbridgedFoodItem(
                data_type = 'Branded',
                description = 'NUT 'N BERRY MIX',
                fdc_id = 534358,
                food_nutrients = [
                    openapi_client.models.abridged_food_nutrient.AbridgedFoodNutrient(
                        number = 303, 
                        name = 'Iron, Fe', 
                        amount = 0.53, 
                        unit_name = 'mg', 
                        derivation_code = 'LCCD', 
                        derivation_description = 'Calculated from a daily value percentage per serving size measure', )
                    ],
                publication_date = '4/1/2019',
                brand_owner = 'Kar Nut Products Company',
                gtin_upc = '077034085228',
                ndb_number = 7954,
                food_code = '27415110'
            )
        else:
            return AbridgedFoodItem(
                data_type = 'Branded',
                description = 'NUT 'N BERRY MIX',
                fdc_id = 534358,
        )
        """

    def testAbridgedFoodItem(self):
        """Test AbridgedFoodItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
