# coding: utf-8

"""
    Food Data Central API

    The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictInt, StrictStr
from pydantic import Field
from openapi_client.models.abridged_food_nutrient import AbridgedFoodNutrient
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AbridgedFoodItem(BaseModel):
    """
    AbridgedFoodItem
    """ # noqa: E501
    data_type: StrictStr = Field(alias="dataType")
    description: StrictStr
    fdc_id: StrictInt = Field(alias="fdcId")
    food_nutrients: Optional[List[AbridgedFoodNutrient]] = Field(default=None, alias="foodNutrients")
    publication_date: Optional[StrictStr] = Field(default=None, alias="publicationDate")
    brand_owner: Optional[StrictStr] = Field(default=None, description="only applies to Branded Foods", alias="brandOwner")
    gtin_upc: Optional[StrictStr] = Field(default=None, description="only applies to Branded Foods", alias="gtinUpc")
    ndb_number: Optional[StrictInt] = Field(default=None, description="only applies to Foundation and SRLegacy Foods", alias="ndbNumber")
    food_code: Optional[StrictStr] = Field(default=None, description="only applies to Survey Foods", alias="foodCode")
    __properties: ClassVar[List[str]] = ["dataType", "description", "fdcId", "foodNutrients", "publicationDate", "brandOwner", "gtinUpc", "ndbNumber", "foodCode"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AbridgedFoodItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in food_nutrients (list)
        _items = []
        if self.food_nutrients:
            for _item in self.food_nutrients:
                if _item:
                    _items.append(_item.to_dict())
            _dict['foodNutrients'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AbridgedFoodItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dataType": obj.get("dataType"),
            "description": obj.get("description"),
            "fdcId": obj.get("fdcId"),
            "foodNutrients": [AbridgedFoodNutrient.from_dict(_item) for _item in obj.get("foodNutrients")] if obj.get("foodNutrients") is not None else None,
            "publicationDate": obj.get("publicationDate"),
            "brandOwner": obj.get("brandOwner"),
            "gtinUpc": obj.get("gtinUpc"),
            "ndbNumber": obj.get("ndbNumber"),
            "foodCode": obj.get("foodCode")
        })
        return _obj


