# coding: utf-8

"""
    Food Data Central API

    The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictInt, StrictStr
from pydantic import Field
from openapi_client.models.branded_food_item_label_nutrients import BrandedFoodItemLabelNutrients
from openapi_client.models.food_nutrient import FoodNutrient
from openapi_client.models.food_update_log import FoodUpdateLog
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class BrandedFoodItem(BaseModel):
    """
    BrandedFoodItem
    """ # noqa: E501
    fdc_id: StrictInt = Field(alias="fdcId")
    available_date: Optional[StrictStr] = Field(default=None, alias="availableDate")
    brand_owner: Optional[StrictStr] = Field(default=None, alias="brandOwner")
    data_source: Optional[StrictStr] = Field(default=None, alias="dataSource")
    data_type: StrictStr = Field(alias="dataType")
    description: StrictStr
    food_class: Optional[StrictStr] = Field(default=None, alias="foodClass")
    gtin_upc: Optional[StrictStr] = Field(default=None, alias="gtinUpc")
    household_serving_full_text: Optional[StrictStr] = Field(default=None, alias="householdServingFullText")
    ingredients: Optional[StrictStr] = None
    modified_date: Optional[StrictStr] = Field(default=None, alias="modifiedDate")
    publication_date: Optional[StrictStr] = Field(default=None, alias="publicationDate")
    serving_size: Optional[StrictInt] = Field(default=None, alias="servingSize")
    serving_size_unit: Optional[StrictStr] = Field(default=None, alias="servingSizeUnit")
    preparation_state_code: Optional[StrictStr] = Field(default=None, alias="preparationStateCode")
    branded_food_category: Optional[StrictStr] = Field(default=None, alias="brandedFoodCategory")
    trade_channel: Optional[List[StrictStr]] = Field(default=None, alias="tradeChannel")
    gpc_class_code: Optional[StrictInt] = Field(default=None, alias="gpcClassCode")
    food_nutrients: Optional[List[FoodNutrient]] = Field(default=None, alias="foodNutrients")
    food_update_log: Optional[List[FoodUpdateLog]] = Field(default=None, alias="foodUpdateLog")
    label_nutrients: Optional[BrandedFoodItemLabelNutrients] = Field(default=None, alias="labelNutrients")
    __properties: ClassVar[List[str]] = ["fdcId", "availableDate", "brandOwner", "dataSource", "dataType", "description", "foodClass", "gtinUpc", "householdServingFullText", "ingredients", "modifiedDate", "publicationDate", "servingSize", "servingSizeUnit", "preparationStateCode", "brandedFoodCategory", "tradeChannel", "gpcClassCode", "foodNutrients", "foodUpdateLog", "labelNutrients"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BrandedFoodItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in food_nutrients (list)
        _items = []
        if self.food_nutrients:
            for _item in self.food_nutrients:
                if _item:
                    _items.append(_item.to_dict())
            _dict['foodNutrients'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in food_update_log (list)
        _items = []
        if self.food_update_log:
            for _item in self.food_update_log:
                if _item:
                    _items.append(_item.to_dict())
            _dict['foodUpdateLog'] = _items
        # override the default output from pydantic by calling `to_dict()` of label_nutrients
        if self.label_nutrients:
            _dict['labelNutrients'] = self.label_nutrients.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of BrandedFoodItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fdcId": obj.get("fdcId"),
            "availableDate": obj.get("availableDate"),
            "brandOwner": obj.get("brandOwner"),
            "dataSource": obj.get("dataSource"),
            "dataType": obj.get("dataType"),
            "description": obj.get("description"),
            "foodClass": obj.get("foodClass"),
            "gtinUpc": obj.get("gtinUpc"),
            "householdServingFullText": obj.get("householdServingFullText"),
            "ingredients": obj.get("ingredients"),
            "modifiedDate": obj.get("modifiedDate"),
            "publicationDate": obj.get("publicationDate"),
            "servingSize": obj.get("servingSize"),
            "servingSizeUnit": obj.get("servingSizeUnit"),
            "preparationStateCode": obj.get("preparationStateCode"),
            "brandedFoodCategory": obj.get("brandedFoodCategory"),
            "tradeChannel": obj.get("tradeChannel"),
            "gpcClassCode": obj.get("gpcClassCode"),
            "foodNutrients": [FoodNutrient.from_dict(_item) for _item in obj.get("foodNutrients")] if obj.get("foodNutrients") is not None else None,
            "foodUpdateLog": [FoodUpdateLog.from_dict(_item) for _item in obj.get("foodUpdateLog")] if obj.get("foodUpdateLog") is not None else None,
            "labelNutrients": BrandedFoodItemLabelNutrients.from_dict(obj.get("labelNutrients")) if obj.get("labelNutrients") is not None else None
        })
        return _obj


