# coding: utf-8

"""
    Food Data Central API

    The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from openapi_client.models.branded_food_item_label_nutrients import BrandedFoodItemLabelNutrients
from openapi_client.models.food_nutrient import FoodNutrient
from openapi_client.models.food_update_log import FoodUpdateLog

class BrandedFoodItem(BaseModel):
    """
    BrandedFoodItem
    """
    fdc_id: StrictInt = Field(..., alias="fdcId")
    available_date: Optional[StrictStr] = Field(None, alias="availableDate")
    brand_owner: Optional[StrictStr] = Field(None, alias="brandOwner")
    data_source: Optional[StrictStr] = Field(None, alias="dataSource")
    data_type: StrictStr = Field(..., alias="dataType")
    description: StrictStr = Field(...)
    food_class: Optional[StrictStr] = Field(None, alias="foodClass")
    gtin_upc: Optional[StrictStr] = Field(None, alias="gtinUpc")
    household_serving_full_text: Optional[StrictStr] = Field(None, alias="householdServingFullText")
    ingredients: Optional[StrictStr] = None
    modified_date: Optional[StrictStr] = Field(None, alias="modifiedDate")
    publication_date: Optional[StrictStr] = Field(None, alias="publicationDate")
    serving_size: Optional[StrictInt] = Field(None, alias="servingSize")
    serving_size_unit: Optional[StrictStr] = Field(None, alias="servingSizeUnit")
    preparation_state_code: Optional[StrictStr] = Field(None, alias="preparationStateCode")
    branded_food_category: Optional[StrictStr] = Field(None, alias="brandedFoodCategory")
    trade_channel: Optional[conlist(StrictStr)] = Field(None, alias="tradeChannel")
    gpc_class_code: Optional[StrictInt] = Field(None, alias="gpcClassCode")
    food_nutrients: Optional[conlist(FoodNutrient)] = Field(None, alias="foodNutrients")
    food_update_log: Optional[conlist(FoodUpdateLog)] = Field(None, alias="foodUpdateLog")
    label_nutrients: Optional[BrandedFoodItemLabelNutrients] = Field(None, alias="labelNutrients")
    __properties = ["fdcId", "availableDate", "brandOwner", "dataSource", "dataType", "description", "foodClass", "gtinUpc", "householdServingFullText", "ingredients", "modifiedDate", "publicationDate", "servingSize", "servingSizeUnit", "preparationStateCode", "brandedFoodCategory", "tradeChannel", "gpcClassCode", "foodNutrients", "foodUpdateLog", "labelNutrients"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BrandedFoodItem:
        """Create an instance of BrandedFoodItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in food_nutrients (list)
        _items = []
        if self.food_nutrients:
            for _item in self.food_nutrients:
                if _item:
                    _items.append(_item.to_dict())
            _dict['foodNutrients'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in food_update_log (list)
        _items = []
        if self.food_update_log:
            for _item in self.food_update_log:
                if _item:
                    _items.append(_item.to_dict())
            _dict['foodUpdateLog'] = _items
        # override the default output from pydantic by calling `to_dict()` of label_nutrients
        if self.label_nutrients:
            _dict['labelNutrients'] = self.label_nutrients.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BrandedFoodItem:
        """Create an instance of BrandedFoodItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BrandedFoodItem.parse_obj(obj)

        _obj = BrandedFoodItem.parse_obj({
            "fdc_id": obj.get("fdcId"),
            "available_date": obj.get("availableDate"),
            "brand_owner": obj.get("brandOwner"),
            "data_source": obj.get("dataSource"),
            "data_type": obj.get("dataType"),
            "description": obj.get("description"),
            "food_class": obj.get("foodClass"),
            "gtin_upc": obj.get("gtinUpc"),
            "household_serving_full_text": obj.get("householdServingFullText"),
            "ingredients": obj.get("ingredients"),
            "modified_date": obj.get("modifiedDate"),
            "publication_date": obj.get("publicationDate"),
            "serving_size": obj.get("servingSize"),
            "serving_size_unit": obj.get("servingSizeUnit"),
            "preparation_state_code": obj.get("preparationStateCode"),
            "branded_food_category": obj.get("brandedFoodCategory"),
            "trade_channel": obj.get("tradeChannel"),
            "gpc_class_code": obj.get("gpcClassCode"),
            "food_nutrients": [FoodNutrient.from_dict(_item) for _item in obj.get("foodNutrients")] if obj.get("foodNutrients") is not None else None,
            "food_update_log": [FoodUpdateLog.from_dict(_item) for _item in obj.get("foodUpdateLog")] if obj.get("foodUpdateLog") is not None else None,
            "label_nutrients": BrandedFoodItemLabelNutrients.from_dict(obj.get("labelNutrients")) if obj.get("labelNutrients") is not None else None
        })
        return _obj


