# coding: utf-8

"""
    Food Data Central API

    The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr
from openapi_client.models.measure_unit import MeasureUnit

class FoodPortion(BaseModel):
    """
    FoodPortion
    """
    id: Optional[StrictInt] = None
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    data_points: Optional[StrictInt] = Field(None, alias="dataPoints")
    gram_weight: Optional[Union[StrictFloat, StrictInt]] = Field(None, alias="gramWeight")
    min_year_acquired: Optional[StrictInt] = Field(None, alias="minYearAcquired")
    modifier: Optional[StrictStr] = None
    portion_description: Optional[StrictStr] = Field(None, alias="portionDescription")
    sequence_number: Optional[StrictInt] = Field(None, alias="sequenceNumber")
    measure_unit: Optional[MeasureUnit] = Field(None, alias="measureUnit")
    __properties = ["id", "amount", "dataPoints", "gramWeight", "minYearAcquired", "modifier", "portionDescription", "sequenceNumber", "measureUnit"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FoodPortion:
        """Create an instance of FoodPortion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of measure_unit
        if self.measure_unit:
            _dict['measureUnit'] = self.measure_unit.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FoodPortion:
        """Create an instance of FoodPortion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FoodPortion.parse_obj(obj)

        _obj = FoodPortion.parse_obj({
            "id": obj.get("id"),
            "amount": obj.get("amount"),
            "data_points": obj.get("dataPoints"),
            "gram_weight": obj.get("gramWeight"),
            "min_year_acquired": obj.get("minYearAcquired"),
            "modifier": obj.get("modifier"),
            "portion_description": obj.get("portionDescription"),
            "sequence_number": obj.get("sequenceNumber"),
            "measure_unit": MeasureUnit.from_dict(obj.get("measureUnit")) if obj.get("measureUnit") is not None else None
        })
        return _obj


