# coding: utf-8

"""
    Food Data Central API

    The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from openapi_client.models.food_attribute import FoodAttribute

class FoodUpdateLog(BaseModel):
    """
    FoodUpdateLog
    """
    fdc_id: Optional[StrictInt] = Field(None, alias="fdcId")
    available_date: Optional[StrictStr] = Field(None, alias="availableDate")
    brand_owner: Optional[StrictStr] = Field(None, alias="brandOwner")
    data_source: Optional[StrictStr] = Field(None, alias="dataSource")
    data_type: Optional[StrictStr] = Field(None, alias="dataType")
    description: Optional[StrictStr] = None
    food_class: Optional[StrictStr] = Field(None, alias="foodClass")
    gtin_upc: Optional[StrictStr] = Field(None, alias="gtinUpc")
    household_serving_full_text: Optional[StrictStr] = Field(None, alias="householdServingFullText")
    ingredients: Optional[StrictStr] = None
    modified_date: Optional[StrictStr] = Field(None, alias="modifiedDate")
    publication_date: Optional[StrictStr] = Field(None, alias="publicationDate")
    serving_size: Optional[StrictInt] = Field(None, alias="servingSize")
    serving_size_unit: Optional[StrictStr] = Field(None, alias="servingSizeUnit")
    branded_food_category: Optional[StrictStr] = Field(None, alias="brandedFoodCategory")
    changes: Optional[StrictStr] = None
    food_attributes: Optional[conlist(FoodAttribute)] = Field(None, alias="foodAttributes")
    __properties = ["fdcId", "availableDate", "brandOwner", "dataSource", "dataType", "description", "foodClass", "gtinUpc", "householdServingFullText", "ingredients", "modifiedDate", "publicationDate", "servingSize", "servingSizeUnit", "brandedFoodCategory", "changes", "foodAttributes"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FoodUpdateLog:
        """Create an instance of FoodUpdateLog from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in food_attributes (list)
        _items = []
        if self.food_attributes:
            for _item in self.food_attributes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['foodAttributes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FoodUpdateLog:
        """Create an instance of FoodUpdateLog from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FoodUpdateLog.parse_obj(obj)

        _obj = FoodUpdateLog.parse_obj({
            "fdc_id": obj.get("fdcId"),
            "available_date": obj.get("availableDate"),
            "brand_owner": obj.get("brandOwner"),
            "data_source": obj.get("dataSource"),
            "data_type": obj.get("dataType"),
            "description": obj.get("description"),
            "food_class": obj.get("foodClass"),
            "gtin_upc": obj.get("gtinUpc"),
            "household_serving_full_text": obj.get("householdServingFullText"),
            "ingredients": obj.get("ingredients"),
            "modified_date": obj.get("modifiedDate"),
            "publication_date": obj.get("publicationDate"),
            "serving_size": obj.get("servingSize"),
            "serving_size_unit": obj.get("servingSizeUnit"),
            "branded_food_category": obj.get("brandedFoodCategory"),
            "changes": obj.get("changes"),
            "food_attributes": [FoodAttribute.from_dict(_item) for _item in obj.get("foodAttributes")] if obj.get("foodAttributes") is not None else None
        })
        return _obj


