# coding: utf-8

"""
    Food Data Central API

    The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr
from openapi_client.models.retention_factor import RetentionFactor

class InputFoodSurvey(BaseModel):
    """
    applies to Survey (FNDDS). Not all inputFoods will have all fields.  # noqa: E501
    """
    id: Optional[StrictInt] = None
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    food_description: Optional[StrictStr] = Field(None, alias="foodDescription")
    ingredient_code: Optional[StrictInt] = Field(None, alias="ingredientCode")
    ingredient_description: Optional[StrictStr] = Field(None, alias="ingredientDescription")
    ingredient_weight: Optional[Union[StrictFloat, StrictInt]] = Field(None, alias="ingredientWeight")
    portion_code: Optional[StrictStr] = Field(None, alias="portionCode")
    portion_description: Optional[StrictStr] = Field(None, alias="portionDescription")
    sequence_number: Optional[StrictInt] = Field(None, alias="sequenceNumber")
    survey_flag: Optional[StrictInt] = Field(None, alias="surveyFlag")
    unit: Optional[StrictStr] = None
    input_food: Optional[SurveyFoodItem] = Field(None, alias="inputFood")
    retention_factor: Optional[RetentionFactor] = Field(None, alias="retentionFactor")
    __properties = ["id", "amount", "foodDescription", "ingredientCode", "ingredientDescription", "ingredientWeight", "portionCode", "portionDescription", "sequenceNumber", "surveyFlag", "unit", "inputFood", "retentionFactor"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InputFoodSurvey:
        """Create an instance of InputFoodSurvey from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of input_food
        if self.input_food:
            _dict['inputFood'] = self.input_food.to_dict()
        # override the default output from pydantic by calling `to_dict()` of retention_factor
        if self.retention_factor:
            _dict['retentionFactor'] = self.retention_factor.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InputFoodSurvey:
        """Create an instance of InputFoodSurvey from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InputFoodSurvey.parse_obj(obj)

        _obj = InputFoodSurvey.parse_obj({
            "id": obj.get("id"),
            "amount": obj.get("amount"),
            "food_description": obj.get("foodDescription"),
            "ingredient_code": obj.get("ingredientCode"),
            "ingredient_description": obj.get("ingredientDescription"),
            "ingredient_weight": obj.get("ingredientWeight"),
            "portion_code": obj.get("portionCode"),
            "portion_description": obj.get("portionDescription"),
            "sequence_number": obj.get("sequenceNumber"),
            "survey_flag": obj.get("surveyFlag"),
            "unit": obj.get("unit"),
            "input_food": SurveyFoodItem.from_dict(obj.get("inputFood")) if obj.get("inputFood") is not None else None,
            "retention_factor": RetentionFactor.from_dict(obj.get("retentionFactor")) if obj.get("retentionFactor") is not None else None
        })
        return _obj

from openapi_client.models.survey_food_item import SurveyFoodItem
InputFoodSurvey.update_forward_refs()

