# coding: utf-8

"""
    Food Data Central API

    The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from openapi_client.models.food_attribute import FoodAttribute
from openapi_client.models.food_portion import FoodPortion
from openapi_client.models.wweia_food_category import WweiaFoodCategory

class SurveyFoodItem(BaseModel):
    """
    SurveyFoodItem
    """
    fdc_id: StrictInt = Field(..., alias="fdcId")
    datatype: Optional[StrictStr] = None
    description: StrictStr = Field(...)
    end_date: Optional[StrictStr] = Field(None, alias="endDate")
    food_class: Optional[StrictStr] = Field(None, alias="foodClass")
    food_code: Optional[StrictStr] = Field(None, alias="foodCode")
    publication_date: Optional[StrictStr] = Field(None, alias="publicationDate")
    start_date: Optional[StrictStr] = Field(None, alias="startDate")
    food_attributes: Optional[conlist(FoodAttribute)] = Field(None, alias="foodAttributes")
    food_portions: Optional[conlist(FoodPortion)] = Field(None, alias="foodPortions")
    input_foods: Optional[conlist(InputFoodSurvey)] = Field(None, alias="inputFoods")
    wweia_food_category: Optional[WweiaFoodCategory] = Field(None, alias="wweiaFoodCategory")
    __properties = ["fdcId", "datatype", "description", "endDate", "foodClass", "foodCode", "publicationDate", "startDate", "foodAttributes", "foodPortions", "inputFoods", "wweiaFoodCategory"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SurveyFoodItem:
        """Create an instance of SurveyFoodItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in food_attributes (list)
        _items = []
        if self.food_attributes:
            for _item in self.food_attributes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['foodAttributes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in food_portions (list)
        _items = []
        if self.food_portions:
            for _item in self.food_portions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['foodPortions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in input_foods (list)
        _items = []
        if self.input_foods:
            for _item in self.input_foods:
                if _item:
                    _items.append(_item.to_dict())
            _dict['inputFoods'] = _items
        # override the default output from pydantic by calling `to_dict()` of wweia_food_category
        if self.wweia_food_category:
            _dict['wweiaFoodCategory'] = self.wweia_food_category.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SurveyFoodItem:
        """Create an instance of SurveyFoodItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SurveyFoodItem.parse_obj(obj)

        _obj = SurveyFoodItem.parse_obj({
            "fdc_id": obj.get("fdcId"),
            "datatype": obj.get("datatype"),
            "description": obj.get("description"),
            "end_date": obj.get("endDate"),
            "food_class": obj.get("foodClass"),
            "food_code": obj.get("foodCode"),
            "publication_date": obj.get("publicationDate"),
            "start_date": obj.get("startDate"),
            "food_attributes": [FoodAttribute.from_dict(_item) for _item in obj.get("foodAttributes")] if obj.get("foodAttributes") is not None else None,
            "food_portions": [FoodPortion.from_dict(_item) for _item in obj.get("foodPortions")] if obj.get("foodPortions") is not None else None,
            "input_foods": [InputFoodSurvey.from_dict(_item) for _item in obj.get("inputFoods")] if obj.get("inputFoods") is not None else None,
            "wweia_food_category": WweiaFoodCategory.from_dict(obj.get("wweiaFoodCategory")) if obj.get("wweiaFoodCategory") is not None else None
        })
        return _obj

from openapi_client.models.input_food_survey import InputFoodSurvey
SurveyFoodItem.update_forward_refs()

