# coding: utf-8

"""
    Food Data Central API

    The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictInt, StrictStr
from pydantic import Field
from openapi_client.models.food_attribute import FoodAttribute
from openapi_client.models.food_portion import FoodPortion
from openapi_client.models.wweia_food_category import WweiaFoodCategory
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SurveyFoodItem(BaseModel):
    """
    SurveyFoodItem
    """ # noqa: E501
    fdc_id: StrictInt = Field(alias="fdcId")
    datatype: Optional[StrictStr] = None
    description: StrictStr
    end_date: Optional[StrictStr] = Field(default=None, alias="endDate")
    food_class: Optional[StrictStr] = Field(default=None, alias="foodClass")
    food_code: Optional[StrictStr] = Field(default=None, alias="foodCode")
    publication_date: Optional[StrictStr] = Field(default=None, alias="publicationDate")
    start_date: Optional[StrictStr] = Field(default=None, alias="startDate")
    food_attributes: Optional[List[FoodAttribute]] = Field(default=None, alias="foodAttributes")
    food_portions: Optional[List[FoodPortion]] = Field(default=None, alias="foodPortions")
    input_foods: Optional[List[InputFoodSurvey]] = Field(default=None, alias="inputFoods")
    wweia_food_category: Optional[WweiaFoodCategory] = Field(default=None, alias="wweiaFoodCategory")
    __properties: ClassVar[List[str]] = ["fdcId", "datatype", "description", "endDate", "foodClass", "foodCode", "publicationDate", "startDate", "foodAttributes", "foodPortions", "inputFoods", "wweiaFoodCategory"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SurveyFoodItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in food_attributes (list)
        _items = []
        if self.food_attributes:
            for _item in self.food_attributes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['foodAttributes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in food_portions (list)
        _items = []
        if self.food_portions:
            for _item in self.food_portions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['foodPortions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in input_foods (list)
        _items = []
        if self.input_foods:
            for _item in self.input_foods:
                if _item:
                    _items.append(_item.to_dict())
            _dict['inputFoods'] = _items
        # override the default output from pydantic by calling `to_dict()` of wweia_food_category
        if self.wweia_food_category:
            _dict['wweiaFoodCategory'] = self.wweia_food_category.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SurveyFoodItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fdcId": obj.get("fdcId"),
            "datatype": obj.get("datatype"),
            "description": obj.get("description"),
            "endDate": obj.get("endDate"),
            "foodClass": obj.get("foodClass"),
            "foodCode": obj.get("foodCode"),
            "publicationDate": obj.get("publicationDate"),
            "startDate": obj.get("startDate"),
            "foodAttributes": [FoodAttribute.from_dict(_item) for _item in obj.get("foodAttributes")] if obj.get("foodAttributes") is not None else None,
            "foodPortions": [FoodPortion.from_dict(_item) for _item in obj.get("foodPortions")] if obj.get("foodPortions") is not None else None,
            "inputFoods": [InputFoodSurvey.from_dict(_item) for _item in obj.get("inputFoods")] if obj.get("inputFoods") is not None else None,
            "wweiaFoodCategory": WweiaFoodCategory.from_dict(obj.get("wweiaFoodCategory")) if obj.get("wweiaFoodCategory") is not None else None
        })
        return _obj

from openapi_client.models.input_food_survey import InputFoodSurvey
# TODO: Rewrite to not use raise_errors
SurveyFoodItem.model_rebuild(raise_errors=False)

